lingvista/account/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('lingvista.account.views',
    url(r'^settings/$', 'settings', name='settings'),
    url(r'^delivery_settings/$', 'delivery_settings', name='delivery-settings'),
)

lingvista/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from lingvista.api.views import AccountSettingsView

urlpatterns = patterns('lingvista.api.views',
    url(r'^transdef/$', 'transdef', name='api_translate'),
    url(r'^langs/$', 'langs', name='api_langs'),
    url(r'^account/', AccountSettingsView.as_view()),
)

lingvista/transdef/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url


urlpatterns = patterns('lingvista.transdef.views',
    url(r'^trainer/', 'trainer', name='trainer')
)

lingvista/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'lingvista.views.index', name='lingvista-index'),
    url(r'^logout/$', 'lingvista.views.logout_user', name='lingvista-logout'),
    url(r'^account/', include('lingvista.account.urls', namespace='account')),
    url('', include('lingvista.transdef.urls', namespace='transdef')),
    url('', include('social.apps.django_app.urls', namespace='social')),

    url(r'^api/v1/', include('lingvista.api.urls')),
    url(r'^admin/', include(admin.site.urls)),

)

lingvista/account/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

from lingvista.transdef.models import Language


class Account(AbstractUser):
    language = models.ForeignKey(Language, default=lambda: Language.objects.get(isocode='en'),
                                 verbose_name='Default translate language')
    objects = UserManager()


class DeliverySettings(models.Model):
    FREQUENCY_CHOICES = (
        ('day', 'Daily'),
        ('week', 'Weekly'),
        ('month', 'Monthly')
    )
    account = models.OneToOneField(Account, verbose_name='User', related_name='delivery_settings')
    enabled = models.BooleanField('Enable sending', default=True)
    email = models.EmailField('Email to send statistics')
    frequency = models.CharField('Frequency', choices=FREQUENCY_CHOICES,
                                 default=FREQUENCY_CHOICES[0][0], max_length=10)

lingvista/api/models.py
# -*- coding: utf-8 -*-

lingvista/transdef/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models


class Language(models.Model):
    """
    Language avaliable for translation and definition
    """
    class Meta:
        ordering = ['name']

    isocode = models.TextField("ISO language code", max_length=10)
    bingcode = models.TextField("Bing language code", max_length=10)
    wikicode = models.TextField("Wikipedia language code", max_length=10)
    name = models.TextField("Readable name")
    
    def __unicode__(self):
        return self.name


class TransDefLog(models.Model):
    """
    Model stores user search for translation or definition
    """
    class Meta:
        ordering = ['created_at']

    account = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Account', related_name='log')
    source = models.TextField('Source text', max_length=200)
    translation = models.TextField('Translation', max_length=200, null=True)
    definition = models.TextField('Definiton', max_length=200, null=True)
    lang_from = models.ForeignKey('Language', verbose_name='Source language', related_name='source_set')
    lang_to = models.ForeignKey('Language', verbose_name='Target language', related_name='transdef_set')
    created_at = models.DateTimeField('Creation time', auto_now_add=True)

    def __unicode__(self):
        return u'{0}: {1}'.format(self.pk, self.source[:20])

lingvista/account/forms.py
# -*- coding: utf-8 -*-
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from lingvista.account.models import Account, DeliverySettings


class AccountForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.add_input(Submit('submit', 'Save', css_class='btn btn-default'))

    class Meta:
        model = Account
        fields = ('language', )


class DeliverySettingsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(DeliverySettingsForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-4'
        self.helper.add_input(Submit('submit', 'Save', css_class='btn btn-default'))


    class Meta:
        model = DeliverySettings
        exclude = ('account', )

lingvista/account/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

from lingvista.account.forms import AccountForm, DeliverySettingsForm


def settings(request):
    form = AccountForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
    return render(request, 'account/settings.html', {'form': form})


def delivery_settings(request):
    try:
        instance = request.user.delivery_settings
    except ObjectDoesNotExist:
        instance = None
    
    form = DeliverySettingsForm(request.POST or None, instance=instance)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.account = request.user
        obj.save()
    return render(request, 'account/delivery_settings.html', {'form': form})

lingvista/api/views.py
# -*- coding: utf-8 -*-
from rest_framework.decorators import api_view
from rest_framework.generics import get_object_or_404, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from lingvista.api.serializers import AccountSettingsSerializer
from lingvista.account.models import Account
from lingvista.transdef.utils import define, translate, detect_language
from lingvista.transdef.models import Language, TransDefLog



@api_view(['GET'])
def transdef(request):
    """
    Finds translation and definition of source text
    """
    lang_from = request.QUERY_PARAMS.get('lang_from', None)
    lang_to = request.QUERY_PARAMS['lang_to']
    lang_from = get_object_or_404(Language, isocode=lang_from) if lang_from else None
    lang_to = get_object_or_404(Language, isocode=lang_to)
    source = request.QUERY_PARAMS['source']

    if not lang_from:
        lang_from = detect_language(source)
    if lang_from != lang_to:
        translation = translate(source, lang_from, lang_to)
        def_url, def_summary = define(translation, lang_to)
    else:
        translation = None
        def_url, def_summary = define(source, lang_to)
    if request.user.is_authenticated():
        TransDefLog.objects.create(
            account=request.user,
            source=source,
            translation=translation,
            definition=def_summary,
            lang_from=lang_from,
            lang_to=lang_to
        )
    data = {
        'lang_from': lang_from.isocode,
        'lang_to': lang_to.isocode,
        'source': source,
        'translation': translation,
        'definition': def_summary,
        'definition_url': def_url,
    }
    return Response(data)


@api_view(['GET'])
def langs(request):
    """
    Returns supported languages
    """
    languages = Language.objects.all().values_list('isocode', 'name')
    return Response(languages)


class AccountSettingsView(RetrieveUpdateAPIView):
    """
    Shows current user his settings and allows to change it
    via GET, PUT or PATCH queryies
    """
    permission_classes = (IsAuthenticated,)
    queryset = Account.objects.all()
    serializer_class = AccountSettingsSerializer

    def get_object(self, queryset=None):
        return self.request.user

    def get_object_or_none(self):
        return self.request.user

lingvista/transdef/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render

from lingvista.transdef.models import TransDefLog

@login_required
def trainer(request):
    log_list = TransDefLog.objects.filter(account=request.user).select_related('lang_from', 'lang_to')
    return render(request, 'transdef/trainer.html', {
        'log_list': log_list
    })

lingvista/views.py
# -*- coding: utf-8 -*-
from django.db.models import Count
from django.contrib.auth import logout
from django.shortcuts import render, redirect

from lingvista.transdef.models import TransDefLog


def index(request):
    log_list = TransDefLog.objects.filter(account=request.user).select_related('lang_from', 'lang_to')
    return render(request, 'lingvista/index.html', {
        'log_list': log_list
    })


def logout_user(request):
    logout(request)
    return redirect('lingvista-index')

lingvista/templates/base.html
{% load gravatar %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lingvista</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}transdef/js/trainer.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url "lingvista-index" %}">lingvista</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right">
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a class="dropdown-toggle username" data-toggle="dropdown" href="#">
                  {% gravatar user.email 30 %}{{ user.first_name }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url "transdef:trainer" %}">Lingvista trainer</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url "account:settings" %}">Account settings</a></li>
                  <li><a href="{% url "account:delivery-settings" %}">Statistics delivery settings</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url "lingvista-logout" %}">Logout</a></li>
                </ul>
              </li>
            {% else %}
              <li class="auth-link"><a href="{% url "social:begin" backend="github" %}"><i class="icon-github auth-icon"></i> Login with GitHub</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container main">
      {% block content %}{% endblock %}
    </section>

    <footer></footer>
  </body>
</html>